services:
  huh.request.insertTagsListener:
    class: HeimrichHannot\RequestBundle\EventListener\InsertTagsListener
    public: true
    arguments:
      - '@contao.framework'
  huh.request:
    class: HeimrichHannot\RequestBundle\Component\HttpFoundation\Request
    public: true
    arguments:
      - '@contao.framework'
      - '@request_stack'