services:
  _defaults:
    public: true

  huh.request.insertTagsListener:
    class: HeimrichHannot\RequestBundle\EventListener\InsertTagsListener
    arguments:
      - '@contao.framework'

  HeimrichHannot\RequestBundle\Component\HttpFoundation\Request:
    arguments:
      - '@contao.framework'
      - '@request_stack'
      - '@contao.routing.scope_matcher'

  huh.request: '@HeimrichHannot\RequestBundle\Component\HttpFoundation\Request'
